-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 17:58:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xDev` DEFAULT CHARACTER SET utf8 ;
USE `xDev` ;

-- -----------------------------------------------------
-- Table `xDev`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xDev`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xDev`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xDev`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `hora` DATETIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`idpedidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xDev`.`produtos_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xDev`.`produtos_pedidos` (
  `idprodutos_pedidos` INT NOT NULL AUTO_INCREMENT,
  `observacao` VARCHAR(100) NULL,
  `produtos_idprodutos` INT NOT NULL,
  `pedidos_idpedidos` INT NOT NULL,
  PRIMARY KEY (`idprodutos_pedidos`),
  INDEX `fk_produtos_pedidos_produtos_idx` (`produtos_idprodutos` ASC),
  INDEX `fk_produtos_pedidos_pedidos1_idx` (`pedidos_idpedidos` ASC),
  CONSTRAINT `fk_produtos_pedidos_produtos`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `xDev`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `xDev`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `produtos` VALUES (1,"X salada simples",2.00);
INSERT INTO `produtos` VALUES (2,"X salada completo",5.00);
INSERT INTO `produtos` VALUES (3,"X simples",1.50);
INSERT INTO `produtos` VALUES (4,"X coração",9.00);
INSERT INTO `produtos` VALUES (5,"X egg",9.20);
INSERT INTO `produtos` VALUES (6,"Coca-cola lata",3.00);
INSERT INTO `produtos` VALUES (7,"Coca-cola 2 litros",8.00);
INSERT INTO `produtos` VALUES (8,"soda lata",3.00);
INSERT INTO `produtos` VALUES (9,"sprite lata",3.00);
INSERT INTO `produtos` VALUES (10,"suco",3.50);

INSERT INTO `pedidos` (`idpedidos`, `hora`, `status`) VALUES (null, NOW(), 0);
INSERT INTO `pedidos` (`idpedidos`, `hora`, `status`) VALUES (null, NOW(), 0);
INSERT INTO `pedidos` (`idpedidos`, `hora`, `status`) VALUES (null, NOW(), 0);